version: '3.9'

services:
  user-service:
    container_name: user-service
    build:
      context: ./server/services/UserService
    ports:
      - "5000:5000"
    env_file:
      - ./server/services/UserService/.env
    depends_on:
      - postgres
    restart: always

  catalog-service:
    build:
      context: ./server/services/CatalogService
    container_name: catalog-service
    ports:
      - "5001:5001"
    env_file:
      - ./server/services/CatalogService/.env
    volumes:
      - ./server/services/CatalogService/static:/app/static
    depends_on:
      - postgres

  gateway-service:
    build:
      context: ./server/services/gateway-service
    container_name: gateway-service
    ports:
      - "8000:8000"
    env_file:
      - ./server/services/gateway-service/.env
    depends_on:
      - auth-user-service
      - catalog-service



  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_DB: RyazanMarket
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
