version: '3.9'

services:
  user-service:
    container_name: user-service
    build:
      context: ./server/services/UserService
    ports:
      - "5000:5000"
    env_file:
      - ./server/services/UserService/.env
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_DB: RyazanMarket
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
